### ISSUE TITLE
hdf5 visualizing tool

### ISSUE THREAD

**Issue by federicopetronio** [LaboratoryOfPlasmaPhysics/kaa-setup#3]
Can you please add the tool that allows the visualisation of the hdf5 files in JupyterLab? I remember it from last version. Thanks a lot :)

**Comment by jeandet** [comment]
This is not possible for now, this extension isn't compatible with jupyterlab 3 yet.
See [here](https://github.com/jupyterlab/jupyterlab-hdf5/issues/42#issuecomment-912507165)

**Comment by jeandet** [comment]
@federicopetronio restart your kernel and you will be able to use the extension now.
